/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LabelComponent: typeof import('./src/components/LabelComponent.vue')['default']
    MessageComponent: typeof import('./src/components/MessageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserIconButton: typeof import('./src/components/UserIconButton.vue')['default']
  }
}
