/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMessage: typeof import('./src/components/AddMessage.vue')['default']
    LabelComponent: typeof import('./src/components/LabelComponent.vue')['default']
    MessageComponent: typeof import('./src/components/MessageComponent.vue')['default']
    MessageIfram: typeof import('./src/components/MessageIfram.vue')['default']
    MessageIframe: typeof import('./src/components/MessageIframe.vue')['default']
    MessageLabels: typeof import('./src/components/MessageLabels.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserIconButton: typeof import('./src/components/UserIconButton.vue')['default']
  }
}
